/*
 * m6_term_colors.h
 *
 *  Created on: Jul 2, 2013
 *      Author: mgrosvenor
 */
#include <stdarg.h>

#include "../types/types.h"


#ifndef M6_TERM_COLORS_H_
#define M6_TERM_COLORS_H_

//Private definitions, don't use directly
#define M6_TERM_ATTR_RAW_RESET       "0"
#define M6_TERM_ATTR_RAW_BRIGHT      "1"
#define M6_TERM_ATTR_RAW_DIM         "2"
#define M6_TERM_ATTR_RAW_UNDERLINE   "3"
#define M6_TERM_ATTR_RAW_BLINK       "4"
#define M6_TERM_ATTR_RAW_REVERSE     "7"
#define M6_TERM_ATTR_RAW_HIDDEN      "8"

//Private definitions, don't use directly
#define M6_TERM_COL_RAW_BLACK       "0"
#define M6_TERM_COL_RAW_RED         "1"
#define M6_TERM_COL_RAW_GREEN       "2"
#define M6_TERM_COL_RAW_YELLOW      "3"
#define M6_TERM_COL_RAW_BLUE        "4"
#define M6_TERM_COL_RAW_MAGENTA     "5"
#define M6_TERM_COL_RAW_CYAN        "6"
#define M6_TERM_COL_RAW_WHITE       "7"

//Private definitions, don't use directly
#define M6_TERM_COLOR(col) "\x1B[3"col"m"
#define M6_TERM_COLOR_ATTR(col,attr) "\x1B["attr";3"col"m"
#define M6_TERM_ATTR(attr) "\x1B["attr"m"

//Colors to be used by users - Please use directly!
#define M6_TERM_COL_NONE    M6_TERM_ATTR(M6_TERM_ATTR_RAW_RESET)
#define M6_TERM_COL_BLACK   M6_TERM_COLOR(M6_TERM_COL_RAW_BLACK)
#define M6_TERM_COL_BLUE    M6_TERM_COLOR(M6_TERM_COL_RAW_BLUE)
#define M6_TERM_COL_CYAN    M6_TERM_COLOR(M6_TERM_COL_RAW_CYAN)
#define M6_TERM_COL_GREEN   M6_TERM_COLOR(M6_TERM_COL_RAW_GREEN)
#define M6_TERM_COL_MAGENTA M6_TERM_COLOR(M6_TERM_COL_RAW_MAGENTA)
#define M6_TERM_COL_RED M6_TERM_COLOR(M6_TERM_COL_RAW_RED)
#define M6_TERM_COL_WHITE   M6_TERM_COLOR(M6_TERM_COL_RAW_WHITE)
#define M6_TERM_COL_YELLOW  M6_TERM_COLOR(M6_TERM_COL_RAW_YELLOW)

#define M6_TERM_COL_BRIGHT_BLACK   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLACK, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_BLUE    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLUE, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_CYAN    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_CYAN, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_GREEN   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_GREEN, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_MAGENTA M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_MAGENTA, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_RED     M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_RED, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_WHITE   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_WHITE, M6_TERM_ATTR_RAW_BRIGHT)
#define M6_TERM_COL_BRIGHT_YELLOW  M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_YELLOW, M6_TERM_ATTR_RAW_BRIGHT)

#define M6_TERM_COL_DIM_BLACK   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLACK, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_BLUE    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLUE, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_CYAN    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_CYAN, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_GREEN   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_GREEN, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_MAGENTA M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_MAGENTA, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_WHITE   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_WHITE, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_RED     M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_RED, M6_TERM_ATTR_RAW_DIM)
#define M6_TERM_COL_DIM_YELLOW  M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_YELLOW, M6_TERM_ATTR_RAW_DIM)

#define M6_TERM_COL_EMPH_BLACK   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLACK, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_BLUE    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_BLUE, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_CYAN    M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_CYAN, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_GREEN   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_GREEN, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_MAGENTA M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_MAGENTA, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_WHITE   M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_WHITE, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_RED     M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_RED, M6_TERM_ATTR_RAW_UNDERLINE)
#define M6_TERM_COL_EMPH_YELLOW  M6_TERM_COLOR_ATTR(M6_TERM_COL_RAW_YELLOW, M6_TERM_ATTR_RAW_UNDERLINE)


typedef char* m6_colour_t;

int dprintf_color_va(int fd, m6_colour_t color, m6_str format, va_list va);
int dprintf_color(int fd, m6_colour_t color, m6_str format, ...);
int printf_color_va( m6_colour_t color, m6_str format, va_list va);
int printf_color( m6_colour_t color, m6_str format, ...);



#endif /* M6_TERM_COLORS_H_ */
